export {
  authSchema,
  forgotPasswordSchema,
  linkTelegramSchema,
  loginSchema,
  passwordSchema,
  registerSchema,
  resetPasswordSchema,
  setPasswordSchema,
  telegramAuthSchema,
  telegramBotStartSchema,
  telegramBotTokenSchema,
  type ForgotPasswordInput,
  type LoginInput,
  type RegisterInput,
  type ResetPasswordInput,
  type SetPasswordInput,
  type TelegramAuthInput,
  type TelegramBotStartInput,
  type TelegramBotTokenInput
} from "@/lib/validation/auth-schemas";
